// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Gao7fCpOiojFqENc5E9aiYcOmntrhF4',
    appId: '1:965777070058:web:865cada4b78e0d78e90493',
    messagingSenderId: '965777070058',
    projectId: 'automated-parking-fa7c6',
    authDomain: 'automated-parking-fa7c6.firebaseapp.com',
    storageBucket: 'automated-parking-fa7c6.appspot.com',
    measurementId: 'G-DBYMY0T0RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5b9X8828w_S5Klnp5uxGKNRo-OGGOiDo',
    appId: '1:965777070058:android:dbf7e1e0f02e8e40e90493',
    messagingSenderId: '965777070058',
    projectId: 'automated-parking-fa7c6',
    storageBucket: 'automated-parking-fa7c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQAR09mdBL--AiJRHd0fbXQf85HsvVpGg',
    appId: '1:965777070058:ios:52080d918ed4a1f2e90493',
    messagingSenderId: '965777070058',
    projectId: 'automated-parking-fa7c6',
    storageBucket: 'automated-parking-fa7c6.appspot.com',
    iosBundleId: 'com.example.automatedParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQAR09mdBL--AiJRHd0fbXQf85HsvVpGg',
    appId: '1:965777070058:ios:d99df0c90c93882fe90493',
    messagingSenderId: '965777070058',
    projectId: 'automated-parking-fa7c6',
    storageBucket: 'automated-parking-fa7c6.appspot.com',
    iosBundleId: 'com.example.automatedParking.RunnerTests',
  );
}
